openapi: "3.0.0"

paths:
  /verify:
    post:
      description: |
        Sends provided files for verification. 

        The `chosenContract` is the optional index of the contract to be verified and only needed when there are multiple contracts, i.e. multiple metadata.json in the provided body. For example a full hardhat-output contains metadatas of all contracts compiled.
      tags:
        - Stateless Verification
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - address
                - chain
                - files
              properties:
                address:
                  type: string
                  format: address
                  example: "0x00000000219ab540356cBB839Cbe05303d7705Fa"
                chain:
                  type: string
                  format: supported-chainId
                  example: "1"
                files:
                  type: object
                  example:
                    metadata.json: "{...}"
                    SimpleStorage.sol: "pragma solidity ^0.8.0; contract SimpleStorage { function get() public view returns (uint) { return 1; } }"
                creatorTxHash:
                  type: string
                  example: "0xbc2f0848023b6a4b89dd049dadc551428a8e95153bc70d9eee6c14ec843f0a98"
                chosenContract:
                  type: string
                  description: "Optional index for the contract if multiple contracts (i.e. metadata.json files) are present."
                  example: "0" 
          multipart/form-data:
            schema:
              type: object
              required:
                - address
                - chain
              properties:
                address:
                  type: string
                  format: address
                chain:
                  type: string
                  format: supported-chainId
                files:
                  description: This field is required
                  oneOf:
                    - type: string
                    - type: array
                      items:
                        type: string
                    - type: string
                      format: binary
                    - type: array
                      items:
                        type: string
                        format: binary
                creatorTxHash:
                  type: string
                chosenContract:
                  type: string
                  description: "Optional index for the contract if multiple contracts (i.e. metadata.json files) are present."
      responses:
        "200":
          description: The contract has been successfully checked or sourcified
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: array
                    items:
                      type: object
                      properties:
                        address:
                          type: string
                        chainId:
                          type: string
                        status:
                          type: string
                        message:
                          type: string
                        libraryMap:
                          type: object
              examples:
                Perfect Match:
                  value:
                    result:
                      - address: "0x123f681646d4a755815f9cb19e1acc8565a0c2ac"
                        chainId: "1"
                        status: "perfect"
                        libraryMap:
                          lib1: "0x3f681646d4a755815f9cb19e1acc8565a0c2ac"
                          lib2: "0x4f681646d4a755815f9cb19e1acc8565a0c2ac"
                Partial Match:
                  value:
                    result:
                      - address: "0x123f681646d4a755815f9cb19e1acc8565a0c2ac"
                        chainId: "1"
                        status: "partial"
                        libraryMap:
                          lib1: "0x3f681646d4a755815f9cb19e1acc8565a0c2ac"
                          lib2: "0x4f681646d4a755815f9cb19e1acc8565a0c2ac"
                Not Deployed:
                  value:
                    result:
                      - address: "0x123f681646d4a755815f9cb19e1acc8565a0c2ac"
                        chainId: "1"
                        status: "null"
                        message: "Chain #1 does not have a contract deployed at 0x...."
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              examples:
                Metadata not found:
                  value:
                    error: 'Metadata file not found. Did you include "metadata.json"?'
                Bad Formatted Json:
                  value:
                    error: "Unexpected token ' in JSON at position 107"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              examples:
                File Not Found:
                  value:
                    error: "Couldn't extract files from the request. Please make sure you have added files"
        "409":
          description: Conflict - The contract is already partially verified and the verification yieled a partial match. The files won't be saved.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              examples:
                Already Partially Verified:
                  value:
                    error: "The contract 0x00000000219ab540356cBB839Cbe05303d7705Fa on chainId 11155111 is already partially verified. The provided new source code also yielded a partial match and will not be stored unless it's a full match"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              examples:
                Resource Missing:
                  value:
                    error: "Resource missing; unsuccessful fetching: contracts/SingleFile.sol"
                Deployed and recompiled mismatch:
                  value:
                    error: "The deployed and recompiled bytecode don't match."
  /verify-deprecated:
    post:
      description: |
        Sends provided files for verification
      tags:
        - Stateless Verification
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - address
                - chain
                - files
              properties:
                address:
                  type: string
                  format: address
                  example: "0x00000000219ab540356cBB839Cbe05303d7705Fa"
                chain:
                  type: string
                  format: supported-chainId
                  example: "1"
                files:
                  type: object
                  example:
                    metadata.json: "{...}"
                    SimpleStorage.sol: "// file"
                creatorTxHash:
                  type: string
                chosenContract:
                  type: string
                match:
                  type: string
      responses:
        "200":
          description: The contract has been successfully checked or sourcified
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: array
                    items:
                      type: object
                      properties:
                        address:
                          type: string
                        chainId:
                          type: string
                        status:
                          type: string
                        message:
                          type: string
                        libraryMap:
                          type: object
              examples:
                Perfect Match:
                  value:
                    result:
                      - address: "0x123f681646d4a755815f9cb19e1acc8565a0c2ac"
                        chainId: "1"
                        status: "perfect"
                        libraryMap:
                          lib1: "0x3f681646d4a755815f9cb19e1acc8565a0c2ac"
                          lib2: "0x4f681646d4a755815f9cb19e1acc8565a0c2ac"
                Partial Match:
                  value:
                    result:
                      - address: "0x123f681646d4a755815f9cb19e1acc8565a0c2ac"
                        chainId: "1"
                        status: "partial"
                        libraryMap:
                          lib1: "0x3f681646d4a755815f9cb19e1acc8565a0c2ac"
                          lib2: "0x4f681646d4a755815f9cb19e1acc8565a0c2ac"
                Not Deployed:
                  value:
                    result:
                      - address: "0x123f681646d4a755815f9cb19e1acc8565a0c2ac"
                        chainId: "1"
                        status: "null"
                        message: "Chain #1 does not have a contract deployed at 0x...."
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              examples:
                Metadata not found:
                  value:
                    error: 'Metadata file not found. Did you include "metadata.json"?'
                Bad Formatted Json:
                  value:
                    error: "Unexpected token ' in JSON at position 107"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              examples:
                File Not Found:
                  value:
                    error: "Couldn't extract files from the request. Please make sure you have added files"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              examples:
                Resource Missing:
                  value:
                    error: "Resource missing; unsuccessful fetching: contracts/SingleFile.sol"
                Deployed and recompiled mismatch:
                  value:
                    error: "The deployed and recompiled bytecode don't match."