import chai from "chai";
import chaiHttp from "chai-http";
import {
  deployFromBytecodeForCreatorTxHash,
  hookIntoVerificationWorkerRun,
} from "../../helpers/helpers";
import { keccak256 } from "ethers";
import { LocalChainFixture } from "../../helpers/LocalChainFixture";
import { ServerFixture } from "../../helpers/ServerFixture";
import type {
  AnyJsonInput,
  Metadata,
  Transformation,
  TransformationValues,
} from "@ethereum-sourcify/lib-sourcify";
import {
  bytesFromString,
  getCompilerNameFromLanguage,
} from "../../../src/server/services/utils/database-util";
import type { Tables } from "../../../src/server/services/utils/database-util";
import crypto from "crypto";
import type { Bytes, MatchLevel } from "../../../src/server/types";
import sinon from "sinon";
import { splitFullyQualifiedName } from "@ethereum-sourcify/lib-sourcify";
import { toVerificationStatus } from "../../../src/server/services/utils/util";

chai.use(chaiHttp);

export interface VerificationTestCase {
  /*
   * The bytecodes as they would appear onchain.
   * When creating a test case, it is important to ensure that these are exactly
   * how they would appear onchain and are not simply taken from the compiler
   * output. Notably the onchain code and the compiler output differs in these
   * ways (transformations):
   * - libraries must be linked in onchain code
   * - creationBytecode should have constructor arguments appended
   * - deployedBytecode includes immutables
   * - For library contracts: deployedBytecode should have the call protection
   *    placeholder replaced
   */
  onchain: {
    creationBytecode: string;
    deployedBytecode: string;
  };
  /*
   * The input used to send to API v2 for verification.
   * This is an object such that other API input types (e.g., metadata) can be
   * added in the future.
   */
  input: {
    stdJsonInput: AnyJsonInput;
    compilerVersion: string;
    contractIdentifier: string;
  };
  /*
   * The output from the compiler in the format as we store it in the database.
   * It should be generated from compiling exactly the input above.
   */
  output: {
    creationBytecode: string;
    deployedBytecode: string;
    compilationArtifacts: Tables.CompiledContract["compilation_artifacts"];
    creationCodeArtifacts: Tables.CompiledContract["creation_code_artifacts"];
    runtimeCodeArtifacts: Tables.CompiledContract["runtime_code_artifacts"];
    metadata: Metadata;
  };
  /*
   * The verification object includes any fields that are generated by
   * ourselves during verification (i.e., not by the compiler) and are stored
   * in the database.
   */
  verification: {
    creationMatch: MatchLevel;
    runtimeMatch: MatchLevel;
    creationTransformations: Transformation[];
    creationValues: TransformationValues;
    runtimeTransformations: Transformation[];
    runtimeValues: TransformationValues;
  };
}

function toHexString(byteArray: number[]) {
  return Array.from(byteArray, function (byte) {
    return ("0" + (byte & 0xff).toString(16)).slice(-2);
  }).join("");
}

function sha3_256(data: Bytes) {
  const hash = crypto.createHash("sha256");
  hash.update(data);
  return hash.digest("hex");
}

/*
 * This suite aims to provide a uniform way to test that specific edge cases
 * are verified and stored correctly in Sourcify. For example, this includes
 * that transformations are generated correctly and that contracts can still
 * be verified when certain compiler settings are changed. At the moment, it
 * tests for correct storage via querying the database directly and checking
 * the response of API v2. It is meant to be extensible for testing storage
 * on other storage services as well.
 *
 * Each test case takes an object in the form of the VerificationTestCase
 * interface as input. The logic deploys the contract on a local chain and
 * verifies it using API v2. After the verification is complete, it queries
 * and checks all relevant database columns and the API v2
 * /contract/{chainId}/{address} endpoint.
 */
describe("Specific Verification Cases", function () {
  const chainFixture = new LocalChainFixture();
  const serverFixture = new ServerFixture();
  const sandbox = sinon.createSandbox();
  const makeWorkersWait = hookIntoVerificationWorkerRun(sandbox, serverFixture);

  afterEach(async () => {
    sandbox.restore();
  });

  const testVerificationCase = async (testCase: VerificationTestCase) => {
    const { resolveWorkers } = makeWorkersWait();
    const { contractAddress, txHash, blockNumber, txIndex } =
      await deployFromBytecodeForCreatorTxHash(
        chainFixture.localSigner,
        testCase.onchain.creationBytecode,
      );

    const verifyRes = await chai
      .request(serverFixture.server.app)
      .post(`/v2/verify/${chainFixture.chainId}/${contractAddress}`)
      .send({
        contractIdentifier: testCase.input.contractIdentifier,
        creationTransactionHash: txHash,
        stdJsonInput: testCase.input.stdJsonInput,
        compilerVersion: testCase.input.compilerVersion,
      });

    chai.expect(verifyRes.status).to.equal(202);
    await resolveWorkers();

    await assertDatabase(
      testCase,
      contractAddress,
      txHash,
      blockNumber,
      txIndex,
    );
  };

  const assertDatabase = async (
    testCase: VerificationTestCase,
    address: string,
    txHash: string,
    blockNumber: number | null,
    txIndex: number | undefined,
  ) => {
    if (!serverFixture.sourcifyDatabase) {
      chai.assert.fail("No database on StorageService");
    }
    const addressBuffer = Buffer.from(address.substring(2), "hex");
    const res = await serverFixture.sourcifyDatabase.query(
      `SELECT
          vc.creation_match,
          vc.creation_values,
          vc.creation_transformations,
          vc.creation_metadata_match,
          vc.runtime_match,
          vc.runtime_values,
          vc.runtime_transformations,
          vc.runtime_metadata_match,
          sm.creation_match as sourcify_creation_match,
          sm.runtime_match as sourcify_runtime_match,
          sm.metadata,
          compiled_runtime_code.code as compiled_runtime_code,
          compiled_creation_code.code as compiled_creation_code,
          compiled_runtime_code.code_hash as compiled_runtime_code_hash,
          compiled_creation_code.code_hash as compiled_creation_code_hash,
          compiled_runtime_code.code_hash_keccak as compiled_runtime_code_hash_keccak,
          compiled_creation_code.code_hash_keccak as compiled_creation_code_hash_keccak,
          onchain_runtime_code.code as onchain_runtime_code,
          onchain_creation_code.code as onchain_creation_code,
          onchain_runtime_code.code_hash as onchain_runtime_code_hash,
          onchain_creation_code.code_hash as onchain_creation_code_hash,
          onchain_runtime_code.code_hash_keccak as onchain_runtime_code_hash_keccak,
          onchain_creation_code.code_hash_keccak as onchain_creation_code_hash_keccak,
          cc.compiler,
          cc.version,
          cc.language,
          cc.name,
          cc.fully_qualified_name,
          cc.compiler_settings,
          cc.compilation_artifacts,
          cc.creation_code_artifacts,
          cc.runtime_code_artifacts,
          cd.chain_id,
          cd.address,
          cd.transaction_hash,
          cd.block_number,
          cd.transaction_index,
          cd.deployer
        FROM verified_contracts vc
        JOIN sourcify_matches sm ON sm.verified_contract_id = vc.id
        LEFT JOIN contract_deployments cd ON cd.id = vc.deployment_id
        LEFT JOIN contracts c ON c.id = cd.contract_id
        LEFT JOIN compiled_contracts cc ON cc.id = vc.compilation_id
        LEFT JOIN code compiled_runtime_code ON compiled_runtime_code.code_hash = cc.runtime_code_hash
        LEFT JOIN code compiled_creation_code ON compiled_creation_code.code_hash = cc.creation_code_hash
        LEFT JOIN code onchain_runtime_code ON onchain_runtime_code.code_hash = c.runtime_code_hash
        LEFT JOIN code onchain_creation_code ON onchain_creation_code.code_hash = c.creation_code_hash
        where cd.address = $1`,
      [addressBuffer],
    );
    const resSources = await serverFixture.sourcifyDatabase.query(
      `SELECT
          ccs.*,
          s.*
        FROM verified_contracts vc
        LEFT JOIN contract_deployments cd ON cd.id = vc.deployment_id
        LEFT JOIN compiled_contracts cc ON cc.id = vc.compilation_id
        LEFT JOIN compiled_contracts_sources ccs on ccs.compilation_id = cc.id
        LEFT JOIN sources s ON s.source_hash = ccs.source_hash
        where cd.address = $1`,
      [addressBuffer],
    );
    chai.expect(res.rowCount).to.equal(1);

    const row = res.rows[0];

    // compiled_contracts columns
    const { contractName } = splitFullyQualifiedName(
      testCase.input.contractIdentifier,
    );
    const compiler = getCompilerNameFromLanguage(
      testCase.input.stdJsonInput.language,
    );
    chai.expect(row.compiler).to.equal(compiler);
    chai.expect(row.version).to.equal(testCase.input.compilerVersion);
    chai
      .expect(row.language)
      .to.equal(testCase.input.stdJsonInput.language.toLowerCase());
    chai.expect(row.name).to.equal(contractName);
    chai
      .expect(row.fully_qualified_name)
      .to.equal(testCase.input.contractIdentifier);
    chai
      .expect(row.compiler_settings)
      .to.deep.equal(testCase.input.stdJsonInput.settings);
    chai
      .expect(row.compilation_artifacts)
      .to.deep.equal(testCase.output.compilationArtifacts);
    chai
      .expect(row.creation_code_artifacts)
      .to.deep.equal(testCase.output.creationCodeArtifacts);
    chai
      .expect(row.runtime_code_artifacts)
      .to.deep.equal(testCase.output.runtimeCodeArtifacts);

    // compiled_contracts -> code columns
    chai
      .expect(`0x${toHexString(row.compiled_creation_code)}`)
      .to.equal(testCase.output.creationBytecode);
    chai
      .expect(`0x${toHexString(row.compiled_runtime_code)}`)
      .to.equal(testCase.output.deployedBytecode);
    chai
      .expect(toHexString(row.compiled_creation_code_hash))
      .to.equal(sha3_256(bytesFromString(testCase.output.creationBytecode)));
    chai
      .expect(toHexString(row.compiled_runtime_code_hash))
      .to.equal(sha3_256(bytesFromString(testCase.output.deployedBytecode)));
    chai
      .expect(`0x${toHexString(row.compiled_creation_code_hash_keccak)}`)
      .to.equal(keccak256(bytesFromString(testCase.output.creationBytecode)));
    chai
      .expect(`0x${toHexString(row.compiled_runtime_code_hash_keccak)}`)
      .to.equal(keccak256(bytesFromString(testCase.output.deployedBytecode)));

    // sources and compiled_contracts_sources columns
    const sources = testCase.input.stdJsonInput.sources;
    const expectedSources: Record<string, string> = {};
    Object.keys(sources).forEach((path) => {
      expectedSources[path] = sources[path].content;
    });
    chai
      .expect(
        resSources.rows.reduce((sources, source) => {
          sources[source.path] = source.content;
          return sources;
        }, {}),
      )
      .to.deep.equal(expectedSources);

    // contract_deployments columns
    chai.expect(row.chain_id).to.equal(chainFixture.chainId);
    chai
      .expect(row.address)
      .to.deep.equal(Buffer.from(address.substring(2), "hex"));
    chai
      .expect(row.transaction_hash)
      .to.deep.equal(Buffer.from(txHash.substring(2), "hex"));
    chai.expect(parseInt(row.block_number)).to.equal(blockNumber);
    chai.expect(parseInt(row.transaction_index)).to.equal(txIndex);
    chai
      .expect(row.deployer)
      .to.deep.equal(
        Buffer.from(chainFixture.localSigner.address.substring(2), "hex"),
      );

    // contract_deployments -> code columns
    chai
      .expect(`0x${toHexString(row.onchain_creation_code)}`)
      .to.equal(testCase.onchain.creationBytecode);
    chai
      .expect(`0x${toHexString(row.onchain_runtime_code)}`)
      .to.equal(testCase.onchain.deployedBytecode);
    chai
      .expect(toHexString(row.onchain_creation_code_hash))
      .to.equal(sha3_256(bytesFromString(testCase.onchain.creationBytecode)));
    chai
      .expect(toHexString(row.onchain_runtime_code_hash))
      .to.equal(sha3_256(bytesFromString(testCase.onchain.deployedBytecode)));
    chai
      .expect(`0x${toHexString(row.onchain_creation_code_hash_keccak)}`)
      .to.equal(keccak256(bytesFromString(testCase.onchain.creationBytecode)));
    chai
      .expect(`0x${toHexString(row.onchain_runtime_code_hash_keccak)}`)
      .to.equal(keccak256(bytesFromString(testCase.onchain.deployedBytecode)));

    // verified_contracts columns
    chai
      .expect(row.creation_match)
      .to.deep.equal(testCase.verification.creationMatch !== null);
    chai
      .expect(row.creation_values)
      .to.deep.equal(testCase.verification.creationValues);
    chai
      .expect(row.creation_transformations)
      .to.deep.equal(testCase.verification.creationTransformations);
    chai
      .expect(row.creation_metadata_match)
      .to.equal(testCase.verification.creationMatch === "exact_match");
    chai
      .expect(row.runtime_match)
      .to.deep.equal(testCase.verification.runtimeMatch !== null);
    chai
      .expect(row.runtime_values)
      .to.deep.equal(testCase.verification.runtimeValues);
    chai
      .expect(row.runtime_transformations)
      .to.deep.equal(testCase.verification.runtimeTransformations);
    chai
      .expect(row.runtime_metadata_match)
      .to.equal(testCase.verification.runtimeMatch === "exact_match");

    // sourcify_matches columns
    chai
      .expect(row.sourcify_creation_match)
      .to.equal(toVerificationStatus(testCase.verification.creationMatch));
    chai
      .expect(row.sourcify_runtime_match)
      .to.equal(toVerificationStatus(testCase.verification.runtimeMatch));
    chai.expect(row.metadata).to.deep.equal(testCase.output.metadata);
  };

  it("Libraries have been linked manually instead of using compiler settings. Placeholders are replaced with zero addresses", async () => {
    const verifierAllianceTestLibrariesManuallyLinked = (
      await import("./testdata/libraries_manually_linked")
    ).default;
    await testVerificationCase(verifierAllianceTestLibrariesManuallyLinked);
  });

  it("Store full match in database", async () => {
    const verifierAllianceTestFullMatch = (
      await import("./testdata/full_match")
    ).default;
    await testVerificationCase(verifierAllianceTestFullMatch);
  });

  it("Store match with immutables in sourcify database", async () => {
    const verifierAllianceTestImmutables = (
      await import("./testdata/immutables")
    ).default;
    await testVerificationCase(verifierAllianceTestImmutables);
  });

  it("Libraries have been linked using compiler settings. The placeholders are already replaced inside the compiled bytecode, and no link references provided", async () => {
    const verifierAllianceTestLibrariesLinkedByCompiler = (
      await import("./testdata/libraries_linked_by_compiler")
    ).default;
    await testVerificationCase(verifierAllianceTestLibrariesLinkedByCompiler);
  });

  it("Store match without auxdata in database", async () => {
    const verifierAllianceTestMetadataHashAbsent = (
      await import("./testdata/metadata_hash_absent")
    ).default;
    await testVerificationCase(verifierAllianceTestMetadataHashAbsent);
  });

  it("Store partial match in database", async () => {
    const verifierAllianceTestPartialMatch = (
      await import("./testdata/partial_match")
    ).default;
    await testVerificationCase(verifierAllianceTestPartialMatch);
  });

  it("Store match deployed with constructor arguments in database", async () => {
    const verifierAllianceTestConstructorArguments = (
      await import("./testdata/constructor_arguments")
    ).default;
    await testVerificationCase(verifierAllianceTestConstructorArguments);
  });

  it("Store partial match in database for a contract with multiple auxdatas", async () => {
    const verifierAllianceTestDoubleAuxdata = (
      await import("./testdata/partial_match_double_auxdata")
    ).default;
    await testVerificationCase(verifierAllianceTestDoubleAuxdata);
  });

  it("Store full match in the database for a contract with multiple auxdatas", async () => {
    const verifierAllianceTestDoubleAuxdata = (
      await import("./testdata/full_match_double_auxdata")
    ).default;
    await testVerificationCase(verifierAllianceTestDoubleAuxdata);
  });

  it("Store Yul match in the database", async () => {
    const verifierAllianceTestYulMatch = (await import("./testdata/yul"))
      .default;
    await testVerificationCase(verifierAllianceTestYulMatch);
  });

  it("Store a partial match in the database when a parameter name was changed", async () => {
    const verifierAllianceTestPartialMatch2 = (
      await import("./testdata/partial_match_2")
    ).default;
    await testVerificationCase(verifierAllianceTestPartialMatch2);
  });

  it("should store auxdata for a Vyper contract compiled with 0.3.4", async () => {
    const vyperTestAuxdata0_3_4 = (
      await import("./testdata/vyper/auxdata-0.3.4")
    ).default;
    await testVerificationCase(vyperTestAuxdata0_3_4);
  });

  it("should store auxdata for a Vyper contract compiled with 0.3.8", async () => {
    const vyperTestAuxdata0_3_8 = (
      await import("./testdata/vyper/auxdata-0.3.8")
    ).default;
    await testVerificationCase(vyperTestAuxdata0_3_8);
  });

  it("should store auxdata for a Vyper contract compiled with 0.4.0", async () => {
    const vyperTestAuxdata0_4_0 = (
      await import("./testdata/vyper/auxdata-0.4.0")
    ).default;
    await testVerificationCase(vyperTestAuxdata0_4_0);
  });

  it("should store auxdata for a Vyper contract compiled with 0.4.1", async () => {
    const vyperTestAuxdata0_4_1 = (
      await import("./testdata/vyper/auxdata-0.4.1")
    ).default;
    await testVerificationCase(vyperTestAuxdata0_4_1);
  });

  it("should store transformations for a Vyper contract with constructor arguments and immutables", async () => {
    const vyperTestConstructorArgumentsAndImmutables = (
      await import("./testdata/vyper/constructor_args_immutables")
    ).default;
    await testVerificationCase(vyperTestConstructorArgumentsAndImmutables);
  });
});
