openapi: "3.0.0"

paths:
  /verify/vyper:
    post:
      description: |
        Sends provided Vyper contract files for verification.
      tags:
        - Stateless Verification
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - address
                - chain
                - files
                - contractPath
                - contractName
                - compilerVersion
              properties:
                address:
                  type: string
                  format: address
                  example: "0x00000000219ab540356cBB839Cbe05303d7705Fa"
                chain:
                  type: string
                  format: supported-chainId
                  example: "1"
                files:
                  type: object
                  example:
                    "test.vy": "# @version >=0.3.2\n\n@external\n@view\ndef helloWorld() -> String[24]:\n    return \"Hello World!\""
                contractPath:
                  type: string
                  example: "test.vy"
                contractName:
                  type: string
                  example: "test"
                compilerVersion:
                  type: string
                  example: "0.8.4+commit.c7e474f2"
                compilerSettings:
                  type: object
                  example:
                    evmVersion: "istanbul"
                    outputSelection:
                      "*": ["evm.bytecode"]
                creatorTxHash:
                  type: string
                  example: "0xbc2f0848023b6a4b89dd049dadc551428a8e95153bc70d9eee6c14ec843f0a98"
      responses:
        "200":
          description: The contract has been successfully checked or sourcified
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: array
                    items:
                      type: object
                      properties:
                        address:
                          type: string
                        chainId:
                          type: string
                        status:
                          type: string
                        message:
                          type: string
              examples:
                Perfect Match:
                  value:
                    result:
                      - address: "0x123f681646d4a755815f9cb19e1acc8565a0c2ac"
                        chainId: "1"
                        status: "perfect"
                Partial Match:
                  value:
                    result:
                      - address: "0x123f681646d4a755815f9cb19e1acc8565a0c2ac"
                        chainId: "1"
                        status: "partial"
                Not Deployed:
                  value:
                    result:
                      - address: "0x123f681646d4a755815f9cb19e1acc8565a0c2ac"
                        chainId: "1"
                        status: "null"
                        message: "Chain #1 does not have a contract deployed at 0x...."
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              examples:
                Vyper Compiler Input Error:
                  value:
                    error: 'Error initializing Vyper compiler input, please check files and settings'
                Bad Formatted Json:
                  value:
                    error: "Unexpected token ' in JSON at position 107"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              examples:
                File Not Found:
                  value:
                    error: "Couldn't extract files from the request. Please make sure you have added files"
        "409":
          description: Conflict - The contract is already partially verified and the verification yieled a partial match. The files won't be saved.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              examples:
                Already Partially Verified:
                  value:
                    error: "The contract 0x00000000219ab540356cBB839Cbe05303d7705Fa on chainId 11155111 is already partially verified. The provided new source code also yielded a partial match and will not be stored unless it's a full match"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              examples:
                Deployed and recompiled mismatch:
                  value:
                    error: "The deployed and recompiled bytecode don't match."